jobs:
- job:
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      git fetch --unshallow
    displayName: 'Convert to non-shallow clone' 

  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      codeCoverageToolOption: 'JaCoCo'
      codeCoverageClassFilesDirectories: 'build/classes/main/'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/build/reports/jacoco/test/jacocoTestReport.xml'
      pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java/'
      reportDirectory: '$(System.DefaultWorkingDirectory)/build/reports/jacoco/test'
      failIfCoverageEmpty: true

- job:
  pool:
    name: 'Default'
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker'
      repository: 'clagosu/spring-clinic'
      command: 'build'
      Dockerfile: '**/Dockerfile'
  
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker'
      repository: 'clagosu/spring-clinic'
      command: 'push'
  
#- job: 
#  pool: 'Default'
#  steps:
#  - task: Kubernetes@1
#    inputs:
#      connectionType: 'None'
#      command: 'apply'
#      arguments: '-f deployment-app.yaml'
#  
#  - script: kubectl port-forward deploy/petclinic-deployment 8086:8085
