trigger:
- feature-ms-CristianMendoza-mensaje
jobs:
- job:
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      git fetch --unshallow
    displayName: 'Convert to non-shallow clone' 

  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build jacocoTestReport'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
    displayName: Build
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/build/reports/jacoco/test/jacocoTestReport.xml'
      pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java/'
      reportDirectory: '$(System.DefaultWorkingDirectory)/build/reports/jacoco/test'
      failIfCoverageEmpty: true
  - task: Docker@2
    inputs:
      containerRegistry: 'docker-cristianmendoza'
      command: 'login'
  - task: Docker@2
    inputs:
      containerRegistry: 'docker-cristianmendoza'
      repository: 'cristianmendoza/testing-web'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
  
- job: 
  pool: 'Default'
  steps:
  - task: Kubernetes@1
    inputs:
      connectionType: 'None'
      command: 'apply'
      arguments: '-f deployment-app.yaml'
  
  - script: kubectl port-forward deploy/microservicio-deployment 8080:8080
