jobs:
- job:
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      git fetch --unshallow
    displayName: 'Convert to non-shallow clone' 

  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      codeCoverageToolOption: 'JaCoCo'
      codeCoverageClassFilesDirectories: 'build/classes/main/'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false

- job:
  pool:
    name: 'Default'
  steps:
  - task: Kubernetes@1
    inputs:
      connectionType: 'None'
      command: 'create'
      arguments: 'deployment microservice --image=cristianmendoza/testing-web'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'

  - script: 'kubectl port-forward deployment/testing-web 8080:8085'
    displayName: 'Redirección de puerto'
