apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-deployment
  labels:
    app: testing-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing-web
  template:
    metadata:
      labels:
        app: testing-web
    spec:
      containers:
      - name: testing-web
        image: cristianmendoza/testing-web:latest
        ports:
        - containerPort: 8080
